<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-17T08:15:49Z" name="Default suite" finished-at="2025-02-17T08:15:57Z" duration-ms="8552">
    <groups>
    </groups>
    <test started-at="2025-02-17T08:15:49Z" name="Default test" finished-at="2025-02-17T08:15:57Z" duration-ms="8552">
      <class name="com.testcases.TC05_DELETE">
        <test-method is-config="true" signature="startReport()[pri:0, instance:com.testcases.TC05_DELETE@49c90a9c]" started-at="2025-02-17T08:15:49Z" name="startReport" finished-at="2025-02-17T08:15:49Z" duration-ms="197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method is-config="true" signature="startTest()[pri:0, instance:com.testcases.TC05_DELETE@49c90a9c]" started-at="2025-02-17T08:15:49Z" name="startTest" finished-at="2025-02-17T08:15:49Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method is-config="true" signature="report()[pri:0, instance:com.testcases.TC05_DELETE@49c90a9c]" started-at="2025-02-17T08:15:49Z" name="report" finished-at="2025-02-17T08:15:49Z" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- report -->
        <test-method signature="deleteEmployee(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.TC05_DELETE@49c90a9c]" started-at="2025-02-17T08:15:49Z" name="deleteEmployee" data-provider="fetchData" finished-at="2025-02-17T08:15:56Z" duration-ms="6943" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://gorest.co.in/public/v2/users]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7702774]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected Status Code: 204, but got: 404]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected Status Code: 204, but got: 404
at org.testng.Assert.fail(Assert.java:96)
at com.commonmethods.Common_Method_DELETE.verifyStatusCode(Common_Method_DELETE.java:45)
at com.testcases.TC05_DELETE.deleteEmployee(TC05_DELETE.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteEmployee -->
        <test-method signature="deleteEmployee(java.lang.String, java.lang.String)[pri:0, instance:com.testcases.TC05_DELETE@49c90a9c]" started-at="2025-02-17T08:15:56Z" name="deleteEmployee" data-provider="fetchData" finished-at="2025-02-17T08:15:57Z" duration-ms="1048" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://gorest.co.in/public/v2/users]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7702775]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected Status Code: 204, but got: 404]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected Status Code: 204, but got: 404
at org.testng.Assert.fail(Assert.java:96)
at com.commonmethods.Common_Method_DELETE.verifyStatusCode(Common_Method_DELETE.java:45)
at com.testcases.TC05_DELETE.deleteEmployee(TC05_DELETE.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteEmployee -->
        <test-method is-config="true" signature="stopReport()[pri:0, instance:com.testcases.TC05_DELETE@49c90a9c]" started-at="2025-02-17T08:15:57Z" name="stopReport" finished-at="2025-02-17T08:15:58Z" duration-ms="238" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopReport -->
      </class> <!-- com.testcases.TC05_DELETE -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
